export const AUDIO_RMS_THRESHOLD = 0.35;
export const IDLE_SAMPLE_INTERVAL = 800; // ms
export const SUSPICION_RECORD_TIME = 25000; // ms
export const DISTRESS_CONFIDENCE_THRESHOLD = 0.8;
export const SUSPICION_COOLDOWN_MS = 8000;
